### ISSUE TITLE
not showing on home app

### ISSUE THREAD

**Issue by toshibochan** [nitaybz/homebridge-onkyo-pioneer#4]
success installed on raspberry pi and is showing on Homebridge web interface and I can control but not showing on home app.

**Comment by jonathanmwood** [comment]
Me too! Had it working previously then it stopped.

**Comment by tbelcher** [comment]
Did you have to change your config file in order to get it to show up?  If so, can you share the config?

Thanks

**Comment by nitaybz** [comment]
it seems like 2 different issues... if the device hasn't showed up from the beginning it's probably because you need to add it manually via the "+" at the top of the Home app, and add accessory. use homebridge code to add the receiver.

@jonathanmwood If it worked before and stopped working I would look at the IP address... if it's not static it might have been changed, another option is that the receiver is not having the "network standby" in it's setting and it's not working while it's closed

**Comment by jonathanmwood** [comment]
@tbelcher @nitaybz I got it to show up again! The IP had indeed reset and was blank. Not sure why that happened, perhaps I didn't save my changes.

I'd like to make sure the AVR's IP address on the network doesn't change. I understand the IP address resetting within the Homebridge plugin is likely caused by something else e.g. not pressing the save button. But I'd like to make sure the AVR's IP is static. I'm unexperienced with these things so I'm not quite sure how to do that. Can anyone help?

**Comment by nitaybz** [comment]
to have the AVR on a static IP it's best to set it up from your router configurations
